server:
  port: 8080

spring:
  ldap:
    embedded:
      port: 8389
      ldif: classpath:users.ldif
      base-dn: "dc=springframework,dc=org"

logging:
  level:
    org.springframework.security: trace
